### ISSUE TITLE
Missing javascript runtime (Ubuntu)

### ISSUE THREAD

**Issue by abinoam** [easydatawarehousing/TryRuby#1]
Same problem as http://stackoverflow.com/questions/9202324/execjs-could-not-find-a-javascript-runtime-but-execjs-and-therubyracer-are-in

Making a pull request in a minute

**Comment by easydatawarehousing** [comment]
I have merged your PR.
Thanks,
Ivo

**Comment by abinoam** [comment]
Thanks :+1:
